from api.models import BidInfo


def add(data):
    for i in data:
        BidInfo.objects.create(
            post_time=i["post_time"],
            project_name=i["project_name"],
            project_detail=i["project_detail"],
            budget=i["budget"],
            start_time=i["start_time"],
            buyer_info=i["buyer_info"],
            project_link=i["project_link"],
        )



data = [
    {
        "post_time": "2023年8月23日",
        "project_name": "2023年8月份第5周双氧水询比采购",
        "project_detail": "采购数量: 180 吨",
        "budget": "/",
        "start_time": "2023年8月29日10:00",
        "buyer_info": "驻马店市白云纸业有限公司",
        "project_link": "",
    },
    {
        "post_time": "2023年8月29日",
        "project_name": "山东华鲁恒升化工股份有限公司尼龙 66 项目水质分析设备采购",
        "project_detail": "(001)A 包: PH、电导率、ORP 分析仪，技术参数详见技术规格书，数量 20 (台/套)(002)B 包: 污水 PH、ORP、溶解氯、污泥浓度计，技术参数详见技术规格书，数量 29(台)套): (003)C 包 污水 COD、氨氮、总磷、总分析仪,技术参数详见技术规格书,数量 4(台套) :(004)D1包: 质量流量计(密度计)，技术参数详见技术规格书，数量 6(台/套):(005)D2 包: 质量流量计(密度计)，技术参数详见技术规格书，数量3(台/套) ;",
        "budget": "/",
        "start_time": "2023年09月20日09时00分",
        "buyer_info": "山东华鲁恒升化工股份有限公司",
        "project_link": "",
    },
    {
        "post_time": "2023年8月29日",
        "project_name": "中国铁塔北京分公司2023年地铁16号线榆树庄北站传统室分设计服务项目",
        "project_detail": "计划对16号线榆树庄北站传统室分勘察设计服务进行补充采购",
        "budget": "24600",
        "start_time": "2023年09月05日09时30分",
        "buyer_info": "中国铁塔股份有限公司北京市分公司",
        "project_link": "",
    },
    {
        "post_time": "2023年8月29日",
        "project_name": "长江路德发包装前蒸汽管网改造工程管材采购",
        "project_detail": "根据采购清单数量运至指定地点。供货方应承担材料运至交货地点的全部费用。",
        "budget": "1100000",
        "start_time": "2023年09月08日9时30分",
        "buyer_info": "菏泽永恒蒸汽运营有限公司",
        "project_link": "",
    },
    {
        "post_time": "2023年8月29日",
        "project_name": "平舆县碧桂园天御府、碧桂园东誉二次供水设备采购项目",
        "project_detail": "(001)平舆县碧桂园天御府二次供水设备采购项目;(002)平奥县碧桂园东誉二次供水设备采购项目;",
        "budget": "2347500",
        "start_time": "2023年09月19日09时00分",
        "buyer_info": "平奥县清源水业有限公司",
        "project_link": "",
    },
    {
        "post_time": "2023年8月29日",
        "project_name": "锦辰园（住宅、公建）再生水工程",
        "project_detail": "dn160 及以下共计1062 米及其它设施",
        "budget": "410000",
        "start_time": "2023年09月08日15时30分",
        "buyer_info": "天津中水有限公司",
        "project_link": "",
    },
    {
        "post_time": "2023年8月29日",
        "project_name": "安康市邮政分公司聘用门卫保安人员服务外包项目",
        "project_detail": "规模: 聘用门卫保安人员 3 名，服务期 2 年，市分公司自筹资金: 15.21 元/工时，聘用3 人，年服务费合计 133200 元。外聘保安作业时间，全年对被服务方指定的区域负责安全保卫，每班执勤时间为八小时。",
        "budget": "133200",
        "start_time": "2023年09月18日09时00分",
        "buyer_info": "中国邮政集团有限公司安康市分公司",
        "project_link": "",
    },
    {
        "post_time": "2023年8月29日",
        "project_name": "丹凤县蘑菇森林农业发展有限公司蒸汽锅炉及蒸汽管网建设项目",
        "project_detail": "规模:2.1建设地点:陕西省商洛市丹风县花镇:2.2程规模: (1)锅炉房建筑面积110m，房屋高度6米，地上1层，框架结构: (2)室外没施: 锅炉房分气缸、DN100管道、地理管道、架空管道。2.3 本次招标工程最高限价1360930.38 元2.4 计划工期;60日历天。2.5招标范围:施工图纸及招标文件工程量清单的所有内容:",
        "budget": "1360930.38",
        "start_time": "2023年09月20日15时00分",
        "buyer_info": "丹凤县蘑菇森林农业发展有限公司",
        "project_link": "",
    },
    {
        "post_time": "2023年8月29日",
        "project_name": "沿大别山高速公路明港至鸡公山段机电工程施工监理",
        "project_detail": "/",
        "budget": "3860000",
        "start_time": "2023年09月20日09时00分",
        "buyer_info": "河南交投大别山明鸡高速公路有限公司",
        "project_link": "",
    },
    {
        "post_time": "2023年8月28日",
        "project_name": "中国铁塔股份有限公司红河州分公司监管系统建设服务项目设备及安装采购项目",
        "project_detail": "提供“中国铁塔股份有限公司红河州分公司监管系统建设服务项目设备及安装采购项目“所需的监控相关设备供货及施工安装调测专线化输等服务",
        "budget": "1668726",
        "start_time": "2023年09月07日14时00分",
        "buyer_info": "中国铁塔股份有限公司云南省分公司",
        "project_link": "",
    },
    {
        "post_time": "2023年8月28日",
        "project_name": "山东华星石油化工集团有限公司公用工程部气柜螺杆压缩机",
        "project_detail": "公用工程部气柜螺杆压缩机采购",
        "budget": "/",
        "start_time": "2023年09月07日09时00分",
        "buyer_info": "山东华星石油化工集团有限公司",
        "project_link": "",
    },
    {
        "post_time": "2023年8月28日",
        "project_name": "舟山铁塔2023年智联业务非标铁塔改造采购项目",
        "project_detail": "采购项目概况:本项目拟采购舟山铁塔所需的简单改造及加支撑构件等所需材料、安装施工采购以及对社会化铁塔巡本次采购预算60万，涉及改造构件材料采购(含税预算20万)，安装施工.采购(含税预算30万)以及对社会化铁塔巡检服务进行采购(含税预算10万元)。",
        "budget": "600000",
        "start_time": "2023年9月5日9时30分",
        "buyer_info": "中国铁塔股份有限公司舟山市分公司",
        "project_link": "",
    },
    {
        "post_time": "2023年8月28日",
        "project_name": "2023年3号机组C级检修#3锅炉C修省煤器输灰管道更换项目",
        "project_detail": "2023 年 3 号机组 C 级检修#3 锅炉 C 修省煤器输灰管道更换项目。具体详见本项目招标技术文件。",
        "budget": "/",
        "start_time": "/",
        "buyer_info": "广东珠海金湾发电有限公司",
        "project_link": "",
    },
    {
        "post_time": "2023年8月28日",
        "project_name": "中国铁塔股份有限公司苏州市分公司5G改造贴壁天线集中采购项目",
        "project_detail": "采购项日概况: 拟对苏州市区存量公路隧道类室分进行改造，拟采用新型贴壁天线方式进行覆盖",
        "budget": "784000",
        "start_time": "2023年09月05日14时00分00秒",
        "buyer_info": "中国铁塔股份有限公司苏州市分公司",
        "project_link": "",
    },
    {
        "post_time": "2023年8月28日",
        "project_name": "中信银行广州分行全辖无线WLAN集成服务采购项目",
        "project_detail": "本次采购标的为分行全辖办公区域及营业区域 wlan 集成服务。",
        "budget": "5241600",
        "start_time": "/",
        "buyer_info": "中信银行股份有限公司广州分行",
        "project_link": "",
    },
    {
        "post_time": "2023年8月28日",
        "project_name": "大数据运营服务综合及风险预警管理平台项目",
        "project_detail": "/",
        "budget": "7000000",
        "start_time": "2023年9月18日09:00",
        "buyer_info": "福建实达集团股份有限公司",
        "project_link": "",
    },
    {
        "post_time": "2023年8月28日",
        "project_name": "山东德州烟草有限公司职工运动会服装购置项目",
        "project_detail": "山东德州烟草有限公司拟为员工定制职工运动会服装",
        "budget": "/",
        "start_time": "2023年09月18日14时00分",
        "buyer_info": "山东德州烟草有限公司",
        "project_link": "",
    },
    {
        "post_time": "2023年8月28日",
        "project_name": "澜沧机场2023年消防车库防油水地胶施工项目",
        "project_detail": "消防车库地面应进行防油、防侵蚀处理，以 1%-2%的坡度向外延伸，并设有排水功能，项目对澜沧景迈机场的消防站现有车库面积约为600m防油水地胶铺设",
        "budget": "/",
        "start_time": "2023年09月04日09时00分",
        "buyer_info": "云南机场集团有限责任公司澜沧景迈机场",
        "project_link": "",
    },
    {
        "post_time": "2023年8月28日",
        "project_name": "华能湖南津市市罗家台羊角汊渔光互补光伏发电项目110KV送出工程",
        "project_detail": "本项目新建一座 110kV 升压汇集站，规划出线一回，接入涂家湖 220kV2.2 规变电站 110KV 侧。110kV 送出线路距离约 20km(实际路径可自行到现场踏勘确定)，导线截面采用 300mm2 钢芯铝绞线,通信采用 2 根 48  0PGW 光缆。同时扩建涂家湖 220kV变电站 110kV 间隔设备、通信系统、保护系统等一、二次设备",
        "budget": "/",
        "start_time": "2023年09月18日09时00分",
        "buyer_info": "中国华能集团有限公司湖南分公司",
        "project_link": "",
    },
    {
        "post_time": "2023年8月28日",
        "project_name": "徐州华开热力有限公司西区换热站、和平路东延高温水工程变更增加管道及管件",
        "project_detail": "项目规模:徐州华开热力有限公司是以供水、供热及管网施工等技术服务为一体专业公司。",
        "budget": "/",
        "start_time": "2023-9-11 9:00",
        "buyer_info": "徐州华开热力有限公司",
        "project_link": "",
    },
    {
        "post_time": "2023年8月28日",
        "project_name": "职工疗养项目",
        "project_detail": "服务期限:不超过2年(自合同签订之日起至2024年12月31日)",
        "budget": "2500人/年",
        "start_time": "2023-9-18 9:00",
        "buyer_info": "中国工商银行股份有限公司厦门市分行",
        "project_link": "",
    },
    {
        "post_time": "2023年8月25日",
        "project_name": "新能源车营运性质识别风控项目",
        "project_detail": "采购内容简述:本项目拟选定 1 家供应商，为采购人提供提供车辆使用性质识别服务，并提供服务对接及运维服务工作",
        "budget": "271500",
        "start_time": "2023年8月31日09时30分",
        "buyer_info": "中国人民财产保险股份有限公司江苏省分公司",
        "project_link": "",
    },
    {
        "post_time": "2023年8月25日",
        "project_name": "杨高南路288号14层员工活动室运动器械采购项目",
        "project_detail": "/",
        "budget": "350000",
        "start_time": "2023年08月31日14时00分",
        "buyer_info": "中证中小投资者服务中心有限责任公司",
        "project_link": "",
    },
    {
        "post_time": "2023年8月25日",
        "project_name": "美丽街区建设",
        "project_detail": "主要内容包括垃圾外运、拆除工程、墙面翻新、花坛整理等绿化工程、灯具等安装工程",
        "budget": "834279",
        "start_time": "2023年09月05日14:00:00",
        "buyer_info": "上海市浦东新区人民政府沪东新村街道办事处",
        "project_link": "",
    },
    {
        "post_time": "2023年8月25日",
        "project_name": "数字克拉玛依系统保障运维项目",
        "project_detail": "/",
        "budget": "226800",
        "start_time": "2023年08月30日17时00分",
        "buyer_info": "数字丝路新疆产业投资集团有限公司",
        "project_link": "",
    },
    {
        "post_time": "2023年8月25日",
        "project_name": "深度学习GPU集群支撑系统",
        "project_detail": "深度学习 GPU 集群支撑系统，为智能算法开发人员、业务算法探索分析人员，提供情报处理领域机器学习、深度学习智能算法的可视化开发运行平台，拥有高性能 GPU\CPU\内存硬件资源和存储服务器，支持数据标注、模型搭建、算法训练、模型管理、模型发布、生产部署、GPU 资源管理等功能，内置丰富的预训练模型和行业项目实例，提供高性能计算支撑平台。",
        "budget": "/",
        "start_time": "2023年09月15日9时30分",
        "buyer_info": "中国电子科技集团公司第一研究所",
        "project_link": "",
    },
    {
        "post_time": "2023年8月25日",
        "project_name": "未来湖畔·捌号院监理服务",
        "project_detail": "未来湖畔·捌号院项目位于信阳市新三路以南、A5 路以北、新三十四大街街以东、新三十六大街以西，占地约 50.19 亩，总建筑面积约 111630.64m’，主要建设住宅，部分采用装配式构件，装修材料采用绿色、无醛板材等，主要设备为节能型电梯、水泵、风机等。",
        "budget": "/",
        "start_time": "2023年9月15日9时30分",
        "buyer_info": "信阳丰信置业有限公司",
        "project_link": "",
    },
    {
        "post_time": "2023年8月25日",
        "project_name": "上饶市广丰区黑滑石产业精加工项目（二期）",
        "project_detail": "总建筑面积9293.86m;最大单体面积8391.09m;最大高度:23.3m; 最大单体跨度:61.3m; 最高层数: 1层",
        "budget": "39210700",
        "start_time": "2023-9-13 9:00",
        "buyer_info": "上饶市广丰区强基科技实业有限公司",
        "project_link": "",
    },
    {
        "post_time": "2023年8月25日",
        "project_name": "上海白云观修缮工程",
        "project_detail": "/",
        "budget": "9990600",
        "start_time": "2023年09月18日14时00分",
        "buyer_info": "上海白云观",
        "project_link": "",
    },
    {
        "post_time": "2023年8月25日",
        "project_name": "大连公交客运集团工会十一物资采购项目",
        "project_detail": "规模: 大连公交客运集团工会一一物资采购，人员数量为11250人",
        "budget": "2688750",
        "start_time": "2023年09月15日09时30分",
        "buyer_info": "大连公交客运集团有限公司工会委员会",
        "project_link": "",
    },
]


# add(data)