# Generated by Django 3.1.2 on 2023-12-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BidInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_time', models.CharField(max_length=255, verbose_name='发布时间')),
                ('project_name', models.TextField(verbose_name='项目名称')),
                ('project_detail', models.TextField(verbose_name='项目概况')),
                ('budget', models.CharField(max_length=255, verbose_name='预算金额')),
                ('start_time', models.CharField(max_length=255, verbose_name='开标时间')),
                ('buyer_info', models.CharField(max_length=255, verbose_name='采购人信息')),
                ('project_link', models.CharField(max_length=255, verbose_name='项目链接')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='日期')),
            ],
            options={
                'verbose_name': 'bid_info',
                'verbose_name_plural': 'bid_info',
                'db_table': 'bid_info',
                'ordering': ['-id'],
            },
        ),
    ]
