# Generated by Django 3.1.2 on 2023-12-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_number', models.CharField(max_length=255, unique=True, verbose_name='项目编号')),
                ('project_link', models.TextField(verbose_name='项目链接')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='日期')),
            ],
            options={
                'verbose_name': 'project_list',
                'verbose_name_plural': 'project_list',
                'db_table': 'project_list',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='bidinfo',
            name='project_link',
            field=models.TextField(verbose_name='项目链接'),
        ),
    ]
